version: '3.8'

services:
  # Frontends
  manufacturer-frontend:
    build: ./EY-Manufacturer-frontend
    ports:
      - "3002:80"
    networks:
      - ey-network
    depends_on:
      - backend

  oem-frontend:
    build: ./EY-OEM-frontend
    ports:
      - "3001:80"
    networks:
      - ey-network
    depends_on:
      - backend

  customer-frontend:
    build: ./EY-customer-frontend
    ports:
      - "3000:80"
    networks:
      - ey-network
    depends_on:
      - backend

  # Backend
  backend:
    build: ./EY-Backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/ey_telematics_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db
    networks:
      - ey-network

  # Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ey_telematics_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ey-network

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ey-network

volumes:
  postgres_data:
  n8n_data:


networks:
  ey-network:
    driver: bridge
